import sqlite3
import tempfile
import unittest
from pathlib import Path

from app import scrim_db


class ScrimDatabaseTest(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.db_file = Path(self.temp_dir.name) / "scrim.db"
        scrim_db.init_db(self.db_file)

    def tearDown(self):
        self.temp_dir.cleanup()

    def test_schema_seeds_named_admins(self):
        with scrim_db.connect(self.db_file) as connection:
            admins = connection.execute(
                "SELECT name, role FROM users WHERE role = 'ADMIN' ORDER BY name"
            ).fetchall()
        self.assertEqual(
            [(row["name"], row["role"]) for row in admins],
            [("서세진", "ADMIN"), ("장원혁", "ADMIN")],
        )

    def test_postgres_schema_removes_sqlite_autoincrement(self):
        schema = scrim_db.postgres_schema_sql()
        self.assertNotIn("AUTOINCREMENT", schema)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", schema)

    def test_roster_scores_follow_tier_and_preferred_line_order(self):
        with scrim_db.connect(self.db_file) as connection:
            entry = scrim_db.upsert_roster_entry(
                connection,
                source_row=2,
                name="점수 테스트",
                tier="D3",
                preferred_lines="정글,미드,원딜",
                top_adjustment="+1",
                game_count_adjustment="-0.5",
            )
            self.assertIsNone(entry["score_top"])
            self.assertEqual(entry["score_jungle"], "35.4")
            self.assertEqual(entry["score_mid"], "34.8")
            self.assertEqual(entry["score_adc"], "35.0")
            self.assertIsNone(entry["score_support"])
            self.assertEqual(
                scrim_db.roster_positions(entry["preferred_lines"]),
                ["JUG", "MID", "ADC"],
            )
            self.assertEqual(
                scrim_db.roster_positions("정글,미드,원딜,서폿"),
                ["JUG", "MID", "ADC", "SUP"],
            )

            updated = scrim_db.update_roster_entry(
                connection,
                entry["id"],
                {"tier": "GOLD IV", "preferred_lines": "탑,서폿"},
            )
            self.assertEqual(updated["score_top"], "15.1")
            self.assertEqual(updated["score_support"], "16.1")
            self.assertIsNone(updated["score_jungle"])

    def test_roster_identity_prefers_scored_case_insensitive_riot_row(self):
        with scrim_db.connect(self.db_file) as connection:
            user = scrim_db.create_user(
                connection,
                name="Case Match",
                riot_id="case-match#kr1",
                password="1234",
                approved=True,
            )
            scrim_db.upsert_roster_entry(
                connection,
                source_row=2,
                name="Case Match",
                riot_id="case-match#KR1",
                tier="D3",
                preferred_lines="정글,미드",
            )
            sync = scrim_db.sync_roster_member_from_approval(connection, user["id"])
            self.assertEqual(sync["linked"], 0)
            entry = scrim_db.get_roster_entry_by_user_identity(
                connection, user["id"], user["riot_id"]
            )
            self.assertEqual(entry["user_id"], user["id"])
            self.assertEqual(entry["tier"], "D3")
            self.assertEqual(entry["score_jungle"], "34.9")

    def test_same_name_is_allowed_but_duplicate_riot_id_is_rejected(self):
        with scrim_db.connect(self.db_file) as connection:
            first = scrim_db.create_user(
                connection,
                name="Haram",
                riot_id="haram#KR1",
                password="1234",
            )
            second = scrim_db.create_user(
                connection,
                name="Haram",
                riot_id="haram2#KR1",
                password="1234",
            )
            self.assertNotEqual(first["id"], second["id"])
            with self.assertRaisesRegex(ValueError, "Riot ID"):
                scrim_db.create_user(
                    connection,
                    name="Other",
                    riot_id="HARAM#kr1",
                    password="1234",
                )

    def test_roster_rejects_duplicate_riot_id_case_insensitively(self):
        with scrim_db.connect(self.db_file) as connection:
            first = scrim_db.create_roster_entry(
                connection,
                name="Haram One",
                riot_id="haram#kr1",
            )
            with self.assertRaisesRegex(ValueError, "Riot ID"):
                scrim_db.create_roster_entry(
                    connection,
                    name="Haram Two",
                    riot_id="haram#KR1",
                )
            second = scrim_db.create_roster_entry(
                connection,
                name="Haram Three",
                riot_id="haram3#KR1",
            )
            with self.assertRaisesRegex(ValueError, "Riot ID"):
                scrim_db.update_roster_entry(
                    connection,
                    second["id"],
                    {"riot_id": "HARAM#kr1"},
                )
            updated = scrim_db.update_roster_entry(
                connection,
                first["id"],
                {"riot_id": "HARAM#KR1"},
            )
            self.assertEqual(updated["riot_id"], "HARAM#KR1")

    def test_delete_roster_entry_deactivates_unused_user(self):
        with scrim_db.connect(self.db_file) as connection:
            entry = scrim_db.create_roster_entry(
                connection,
                name="Delete Me",
                riot_id="delete-me#KR1",
            )
            user_id = entry["user_id"]
            result = scrim_db.delete_roster_entry(connection, entry["id"])
            user = scrim_db.get_user(connection, user_id)
            self.assertEqual(result["entry"]["id"], entry["id"])
            self.assertFalse(user["is_active"])
            removed = connection.execute(
                "SELECT 1 FROM roster_entries WHERE id = ?",
                (entry["id"],),
            ).fetchone()
            self.assertIsNone(removed)

    def test_team_creator_becomes_leader(self):
        with scrim_db.connect(self.db_file) as connection:
            user = scrim_db.create_user(
                connection,
                name="팀장",
                riot_id="leader#KR1",
                password="1234",
            )
            team = scrim_db.create_team(
                connection,
                name="첫 팀",
                created_by=user["id"],
            )

        self.assertEqual(team["name"], "첫 팀")
        self.assertEqual(team["members"][0]["user_id"], user["id"])
        self.assertEqual(team["members"][0]["role"], "LEADER")
        self.assertTrue(team["invite_code"])

    def test_user_can_have_only_one_active_team(self):
        with scrim_db.connect(self.db_file) as connection:
            user = scrim_db.create_user(
                connection,
                name="한팀",
                riot_id="one-team#KR1",
                password="1234",
            )
            scrim_db.create_team(connection, name="A", created_by=user["id"])
            with self.assertRaisesRegex(ValueError, "이미 활성 팀"):
                scrim_db.create_team(
                    connection,
                    name="B",
                    created_by=user["id"],
                )

    def test_join_by_code_rejects_member_with_active_team(self):
        with scrim_db.connect(self.db_file) as connection:
            leader = scrim_db.create_user(
                connection,
                name="리더",
                riot_id="leader2#KR1",
                password="1234",
            )
            member = scrim_db.create_user(
                connection,
                name="멤버",
                riot_id="member#KR1",
                password="1234",
            )
            other_leader = scrim_db.create_user(
                connection,
                name="다른리더",
                riot_id="leader3#KR1",
                password="1234",
            )
            first = scrim_db.create_team(
                connection,
                name="기존 팀",
                created_by=leader["id"],
            )
            second = scrim_db.create_team(
                connection,
                name="가입할 팀",
                created_by=other_leader["id"],
            )
            scrim_db.join_team_by_code(
                connection,
                invite_code=first["invite_code"],
                user_id=member["id"],
            )
            with self.assertRaisesRegex(ValueError, "이미 활성 팀"):
                scrim_db.join_team_by_code(
                    connection,
                    invite_code=second["invite_code"],
                    user_id=member["id"],
                )

    def test_schedule_overlap_is_rejected(self):
        with scrim_db.connect(self.db_file) as connection:
            user = scrim_db.create_user(
                connection,
                name="예약자",
                riot_id="schedule#KR1",
                password="1234",
            )
            team = scrim_db.create_team(
                connection,
                name="예약 팀",
                created_by=user["id"],
            )
            scrim_db.create_scrim_schedule(
                connection,
                team_id=team["id"],
                scheduled_date="2026-07-07",
                start_time="20:00",
                end_time="21:00",
                created_by=user["id"],
            )
            with self.assertRaisesRegex(ValueError, "이미 예약된 스크림"):
                scrim_db.create_scrim_schedule(
                    connection,
                    team_id=team["id"],
                    scheduled_date="2026-07-07",
                    start_time="20:30",
                    end_time="21:30",
                    created_by=user["id"],
                )

    def test_partial_unique_index_blocks_duplicate_active_membership(self):
        with scrim_db.connect(self.db_file) as connection:
            user = scrim_db.create_user(
                connection,
                name="DB규칙",
                riot_id="db-rule#KR1",
                password="1234",
            )
            leader = scrim_db.create_user(
                connection,
                name="리더4",
                riot_id="leader4#KR1",
                password="1234",
            )
            first = scrim_db.create_team(
                connection,
                name="첫번째",
                created_by=user["id"],
            )
            second = scrim_db.create_team(
                connection,
                name="두번째",
                created_by=leader["id"],
            )
            with self.assertRaises(sqlite3.IntegrityError):
                connection.execute(
                    """
                    INSERT INTO team_members (team_id, user_id, role)
                    VALUES (?, ?, 'MEMBER')
                    """,
                    (second["id"], user["id"]),
                )
            self.assertEqual(first["members"][0]["role"], "LEADER")


if __name__ == "__main__":
    unittest.main()
